// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20260329042550_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.WeatherRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Humidity")
                        .HasColumnType("float");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("float");

                    b.Property<double>("WindSpeedKmh")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("WeatherRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "New York",
                            Condition = "Sunny",
                            Humidity = 55.0,
                            RecordedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TemperatureCelsius = 22.5,
                            WindSpeedKmh = 15.0
                        },
                        new
                        {
                            Id = 2,
                            City = "London",
                            Condition = "Cloudy",
                            Humidity = 72.0,
                            RecordedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TemperatureCelsius = 14.0,
                            WindSpeedKmh = 20.0
                        },
                        new
                        {
                            Id = 3,
                            City = "Tokyo",
                            Condition = "Rainy",
                            Humidity = 85.0,
                            RecordedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TemperatureCelsius = 18.0,
                            WindSpeedKmh = 10.0
                        },
                        new
                        {
                            Id = 4,
                            City = "Sydney",
                            Condition = "Partly Cloudy",
                            Humidity = 60.0,
                            RecordedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TemperatureCelsius = 26.0,
                            WindSpeedKmh = 25.0
                        },
                        new
                        {
                            Id = 5,
                            City = "Paris",
                            Condition = "Clear",
                            Humidity = 50.0,
                            RecordedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TemperatureCelsius = 19.5,
                            WindSpeedKmh = 12.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
